# -*- coding: utf-8 -*-
"""Source code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyb8dUkIMMY5qinlH91gxm-PHxsoeWrN
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **upload the dataset**"""

from google.colab import files
uploaded = files.upload()

"""# **Load the dataset**"""

import pandas as pd

df = pd.read_csv('final_updated_shopping_trends.csv')

"""# **Data Exploration**"""

# read the dataset
print(df.head())

# shaoe of the dataset
print("shape:",df.shape)

#colunm names
print("columns:",df.columns)

#Data types and non-null values
print(df.info())

# Summary statistics for numeric features
print(df.describe())

"""# **Check for Missing Values and Duplicates**"""

# Check for missing values
print(df.isnull().sum())

# Check for duplicates
print("Duplicate rows:", df.duplicated().sum())

"""# **Visualization**"""

# Age Distribution
plt.figure(figsize=(8, 5))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Gender Count
plt.figure(figsize=(6, 4))
sns.countplot(x='Gender', data=df)
plt.title('Gender Count')
plt.show()

# age by gender
plt.figure(figsize=(8, 5))
sns.boxplot(x='Gender', y='Age', data=df)
plt.title('Boxplot of Age by Gender')
plt.show()

#Purchase Amount Distribution
plt.figure(figsize=(8, 5))
sns.histplot(df['Purchase Amount (USD)'], bins=30, kde=True)
plt.title('Distribution of Purchase Amount')
plt.xlabel('Purchase Amount (USD)')
plt.show()

# Review Ratings
plt.figure(figsize=(8, 5))
sns.histplot(df['Review Rating'], bins=10, kde=True)
plt.title('Review Rating Distribution')
plt.xlabel('Review Rating')
plt.show()

# Popular Categories
plt.figure(figsize=(10, 6))
sns.countplot(y='Category', data=df, order=df['Category'].value_counts().index)
plt.title('Most Purchased Product Categories')
plt.show()

# Seasonal Trends
plt.figure(figsize=(8, 5))
sns.countplot(x='Season', data=df, order=df['Season'].value_counts().index)
plt.title('Purchases by Season')
plt.show()

# Payment Method Preference
plt.figure(figsize=(10, 6))
sns.countplot(y='Payment Method', data=df, order=df['Payment Method'].value_counts().index)
plt.title('Preferred Payment Methods')
plt.show()

"""
# **Identify Target and Features**"""

target = 'Purchase Amount (USD)'
features = df.columns.drop(target)
print("Features:", features)

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical Columns:", categorical_cols.tolist())

df_encoded = pd.get_dummies(df, drop_first=True)

